import { Router } from 'express';
import { prisma } from '../src/prisma.js';
import { auth, permit } from '../src/middleware.js';
import { audit, nextSequenceNo } from '../src/utils.js';
const r=Router();r.use(auth);const n=v=>Number(v||0);const round2=v=>Math.round((n(v)+Number.EPSILON)*100)/100;

async function refreshInvoice(tx,invoiceId){const inv=await tx.salesInvoice.findUnique({where:{id:invoiceId}});const [a,cr]=await Promise.all([tx.salesPayment.aggregate({where:{invoiceId},_sum:{amount:true}}),tx.salesReturn.aggregate({where:{invoiceId},_sum:{creditAmount:true}})]);const paid=round2(a._sum.amount||0),credit=round2(cr._sum.creditAmount||0),net=Math.max(0,round2(n(inv.totalAmount)-credit)),out=Math.max(0,round2(net-paid));const status=out<=0?'PAID':paid>0||credit>0?'PARTIALLY_PAID':'ISSUED';await tx.salesInvoice.update({where:{id:invoiceId},data:{amountPaid:paid,outstanding:out,status}});return {paid,credit,net,outstanding:out,status};}
function displayStatus(c){if(c.status!=='HELD')return c.status;return new Date(c.expectedPresentationDate)<=new Date()?'DUE':'NOT YET DUE';}

r.get('/',permit('CHEQUE_VIEW'),async(req,res)=>{const where={};if(req.query.status&& !['DUE','NOT YET DUE'].includes(req.query.status))where.status=req.query.status;const rows=await prisma.customerCheque.findMany({where,include:{customer:{select:{name:true,customerCode:true}},invoice:{select:{invoiceNo:true,outstanding:true}}},orderBy:{dateReceived:'desc'}});let out=rows.map(x=>({...x,amount:n(x.amount),displayStatus:displayStatus(x)}));if(req.query.status==='DUE'||req.query.status==='NOT YET DUE')out=out.filter(x=>x.displayStatus===req.query.status);res.json(out);});

r.post('/',permit('CHEQUE_CREATE'),async(req,res)=>{try{const inv=await prisma.salesInvoice.findUnique({where:{id:req.body.invoiceId}});if(!inv||inv.status==='CANCELLED')return res.status(404).json({message:'Active invoice not found.'});const amount=round2(req.body.amount);if(amount<=0)return res.status(400).json({message:'Cheque amount must be greater than zero.'});const pending=await prisma.customerCheque.aggregate({where:{invoiceId:inv.id,status:{in:['HELD','PRESENTED']}},_sum:{amount:true}});const uncovered=Math.max(0,n(inv.outstanding)-n(pending._sum.amount));if(amount>uncovered)return res.status(400).json({message:`Cheque exceeds uncovered invoice balance of NGN ${uncovered.toLocaleString()}.`});const chequeCode=(await nextSequenceNo('CHEQUE','CHQ',6)).replaceAll('/','-');const row=await prisma.customerCheque.create({data:{chequeCode,invoiceId:inv.id,customerId:inv.customerId,chequeNo:String(req.body.chequeNo||'').trim(),drawerBank:String(req.body.drawerBank||'').trim(),amount,dateReceived:req.body.dateReceived?new Date(req.body.dateReceived):new Date(),chequeDate:new Date(req.body.chequeDate),expectedPresentationDate:new Date(req.body.expectedPresentationDate),remarks:String(req.body.remarks||'').trim()||null,createdById:req.user.id}});await audit(req.user.id,'REGISTER_CHEQUE','CHEQUE',row.id,{chequeCode,invoiceNo:inv.invoiceNo,amount},req.ip);res.json(row);}catch(e){res.status(400).json({message:e.message});}});

r.post('/:id/present',permit('CHEQUE_PRESENT'),async(req,res)=>{const c=await prisma.customerCheque.findUnique({where:{id:req.params.id}});if(!c)return res.status(404).json({message:'Cheque not found.'});if(c.status!=='HELD')return res.status(409).json({message:'Only HELD cheques can be presented.'});const row=await prisma.customerCheque.update({where:{id:c.id},data:{status:'PRESENTED',datePresented:new Date(),updatedById:req.user.id}});await audit(req.user.id,'PRESENT_CHEQUE','CHEQUE',c.id,{chequeCode:c.chequeCode},req.ip);res.json(row);});

r.post('/:id/bounce',permit('CHEQUE_BOUNCE'),async(req,res)=>{const c=await prisma.customerCheque.findUnique({where:{id:req.params.id}});if(!c)return res.status(404).json({message:'Cheque not found.'});if(c.status!=='PRESENTED')return res.status(409).json({message:'Only PRESENTED cheques can be bounced.'});const reason=String(req.body.reason||'').trim();if(!reason)return res.status(400).json({message:'Bounce reason is required.'});const row=await prisma.customerCheque.update({where:{id:c.id},data:{status:'BOUNCED',dateBounced:new Date(),bounceReason:reason,updatedById:req.user.id}});await audit(req.user.id,'BOUNCE_CHEQUE','CHEQUE',c.id,{reason},req.ip);res.json(row);});

r.post('/:id/cancel',permit('CHEQUE_CANCEL'),async(req,res)=>{const c=await prisma.customerCheque.findUnique({where:{id:req.params.id}});if(!c)return res.status(404).json({message:'Cheque not found.'});if(!['HELD','PRESENTED','BOUNCED'].includes(c.status))return res.status(409).json({message:'This cheque cannot be cancelled in its current status.'});const reason=String(req.body.reason||'').trim();if(!reason)return res.status(400).json({message:'Cancellation reason is required.'});const row=await prisma.customerCheque.update({where:{id:c.id},data:{status:'CANCELLED',dateCancelled:new Date(),cancellationReason:reason,updatedById:req.user.id}});await audit(req.user.id,'CANCEL_CHEQUE','CHEQUE',c.id,{reason},req.ip);res.json(row);});

r.post('/:id/replace',permit('CHEQUE_REPLACE'),async(req,res)=>{try{const old=await prisma.customerCheque.findUnique({where:{id:req.params.id},include:{invoice:true}});if(!old)return res.status(404).json({message:'Cheque not found.'});if(!['BOUNCED','CANCELLED'].includes(old.status))return res.status(409).json({message:'Only BOUNCED or CANCELLED cheques can be replaced.'});const amount=req.body.amount!==undefined?round2(req.body.amount):n(old.amount);if(amount<=0||amount>n(old.invoice.outstanding))return res.status(400).json({message:'Replacement amount is invalid or exceeds invoice outstanding.'});const chequeCode=(await nextSequenceNo('CHEQUE','CHQ',6)).replaceAll('/','-');const result=await prisma.$transaction(async tx=>{const fresh=await tx.customerCheque.create({data:{chequeCode,invoiceId:old.invoiceId,customerId:old.customerId,chequeNo:String(req.body.chequeNo||'').trim(),drawerBank:String(req.body.drawerBank||old.drawerBank).trim(),amount,dateReceived:new Date(),chequeDate:new Date(req.body.chequeDate),expectedPresentationDate:new Date(req.body.expectedPresentationDate),remarks:`Replacement for ${old.chequeCode}`,createdById:req.user.id}});await tx.customerCheque.update({where:{id:old.id},data:{status:'REPLACED',replacementChequeId:fresh.id,updatedById:req.user.id}});return fresh;});await audit(req.user.id,'REPLACE_CHEQUE','CHEQUE',old.id,{old:old.chequeCode,new:chequeCode},req.ip);res.json(result);}catch(e){res.status(400).json({message:e.message});}});

r.post('/:id/clear',permit('CHEQUE_CLEAR'),async(req,res)=>{try{const c=await prisma.customerCheque.findUnique({where:{id:req.params.id},include:{invoice:true}});if(!c)return res.status(404).json({message:'Cheque not found.'});if(c.status!=='PRESENTED')return res.status(409).json({message:'Only PRESENTED cheques can be cleared.'});if(n(c.amount)>n(c.invoice.outstanding))return res.status(409).json({message:'Cheque amount exceeds current invoice outstanding.'});const paymentNo=await nextSequenceNo('SALES_PAYMENT','PAY',6),receiptNo=await nextSequenceNo('RECEIPT','RCT',6),bankTxnNo=await nextSequenceNo('BANK_TXN','BTX',7);const bank=await prisma.companyBank.findUnique({where:{id:String(req.body.companyBankId||'')}});if(!bank||!bank.active)return res.status(400).json({message:'Select the Dariltweens bank account where the cheque cleared.'});const companyBank=`${bank.bankName} | ${bank.accountNumber}`;const result=await prisma.$transaction(async tx=>{const clearedAt=new Date();const p=await tx.salesPayment.create({data:{paymentNo,paymentDate:clearedAt,customerId:c.customerId,invoiceId:c.invoiceId,amount:n(c.amount),method:'CHEQUE',bankId:bank.id,bankAccount:companyBank,reference:c.chequeNo,remarks:`Cleared cheque ${c.chequeCode}`,chequeId:c.id,receivedById:req.user.id}});const receipt=await tx.salesReceipt.create({data:{receiptNo,receiptDate:p.paymentDate,customerId:c.customerId,invoiceId:c.invoiceId,paymentId:p.id,amount:n(c.amount),paymentMethod:'CHEQUE',reference:c.chequeNo,remarks:`Cleared cheque ${c.chequeCode}`,issuedById:req.user.id}});await tx.bankTransaction.create({data:{transactionNo:bankTxnNo,transactionDate:clearedAt,bankId:bank.id,type:'DEPOSIT',amount:n(c.amount),referenceType:'CHEQUE_CLEARING',referenceId:c.id,referenceNo:c.chequeCode,narration:`Cleared customer cheque ${c.chequeNo} for ${c.invoice.invoiceNo}`,createdById:req.user.id}});await tx.companyBank.update({where:{id:bank.id},data:{currentBalance:{increment:n(c.amount)}}});const updated=await tx.customerCheque.update({where:{id:c.id},data:{status:'CLEARED',companyBank,companyBankId:bank.id,dateCleared:clearedAt,updatedById:req.user.id}});const position=await refreshInvoice(tx,c.invoiceId);return {cheque:updated,payment:p,receipt,position};});await audit(req.user.id,'CLEAR_CHEQUE','CHEQUE',c.id,{chequeCode:c.chequeCode,paymentNo,receiptNo,companyBank},req.ip);res.json(result);}catch(e){res.status(400).json({message:e.message});}});

export default r;
