import { Router } from 'express';
import PDFDocument from 'pdfkit';
import { prisma } from '../src/prisma.js';
import { auth, permit } from '../src/middleware.js';

const r=Router();
r.use(auth);
const n=v=>Number(v||0);
const money=v=>`NGN ${n(v).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const d=v=>v?new Date(v).toLocaleDateString('en-GB'):'—';
const safe=s=>String(s??'').replace(/[\r\n]+/g,' ').trim();
const COMPANY='DARILTWEENS NIGERIA LIMITED';
const ACRONYM='DNL';

function pageSpec(size,rowCount=0){
  const s=String(size||'A4').toUpperCase();
  if(s==='A5') return {size:'A5',margin:30,pos:false,label:'A5'};
  if(s==='POS80') return {size:[226.77,Math.max(650,430+rowCount*24)],margin:12,pos:true,label:'80mm POS'};
  if(s==='POS58') return {size:[164.41,Math.max(700,470+rowCount*27)],margin:8,pos:true,label:'58mm POS'};
  return {size:'A4',margin:36,pos:false,label:'A4'};
}
function makeDoc(res,filename,spec){
  res.setHeader('Content-Type','application/pdf');
  res.setHeader('Content-Disposition',`inline; filename="${filename}"`);
  const doc=new PDFDocument({size:spec.size,margins:{top:spec.margin,bottom:spec.margin,left:spec.margin,right:spec.margin},autoFirstPage:true,bufferPages:true});
  doc.pipe(res);return doc;
}
function line(doc,y){doc.moveTo(doc.page.margins.left,y).lineTo(doc.page.width-doc.page.margins.right,y).strokeColor('#C9CED8').lineWidth(.6).stroke();}
function heading(doc,title,ref,spec){
  doc.font('Helvetica-Bold').fontSize(spec.pos?11:15).text(`${ACRONYM} · ${COMPANY}`,{align:'center'});
  doc.moveDown(.15).font('Helvetica-Bold').fontSize(spec.pos?13:22).text(title,{align:'center'});
  if(ref)doc.moveDown(.1).font('Helvetica').fontSize(spec.pos?7:9).text(ref,{align:'center'});
  doc.moveDown(.5);line(doc,doc.y);doc.moveDown(.6);
}
function kv(doc,label,value,spec){doc.font('Helvetica-Bold').fontSize(spec.pos?7:9).text(`${label}: `,{continued:true});doc.font('Helvetica').text(safe(value)||'—');}
function footer(doc,spec){doc.moveDown(.8);line(doc,doc.y);doc.moveDown(.5);doc.font('Helvetica').fontSize(spec.pos?6.5:8).fillColor('#555').text(`Generated by ${ACRONYM} Business System · ${new Date().toLocaleString('en-GB')}`,{align:'center'}).fillColor('#000');}

r.get('/invoices/:id.pdf',permit('INVOICE_VIEW'),async(req,res)=>{
  const x=await prisma.salesInvoice.findUnique({where:{id:req.params.id},include:{customer:true,lines:{include:{item:true,location:true}},payments:true,receipts:true,cheques:true,returns:{include:{refunds:true}}}});
  if(!x)return res.status(404).json({message:'Invoice not found.'});
  const spec=pageSpec(req.query.size,x.lines.length+x.payments.length+x.cheques.length);
  const doc=makeDoc(res,`${x.invoiceNo}_${spec.label.replaceAll(' ','_')}.pdf`,spec);
  heading(doc,'SALES INVOICE',x.invoiceNo,spec);
  kv(doc,'Invoice Date',d(x.invoiceDate),spec);kv(doc,'Due Date',d(x.dueDate),spec);kv(doc,'Status',x.status,spec);
  doc.moveDown(.45);doc.font('Helvetica-Bold').fontSize(spec.pos?8:11).text('BILL TO');
  kv(doc,'Customer',x.customer.name,spec);kv(doc,'Customer Code',x.customer.customerCode,spec);kv(doc,'Phone',x.customer.phone||'—',spec);kv(doc,'Address',x.customer.address||'—',spec);
  doc.moveDown(.55);line(doc,doc.y);doc.moveDown(.5);
  if(spec.pos){
    doc.font('Helvetica-Bold').fontSize(7).text('ITEM / QTY / PRICE / TOTAL');doc.moveDown(.3);
    for(const l of x.lines){doc.font('Helvetica-Bold').fontSize(7).text(safe(l.item.name));if(l.location)doc.font('Helvetica').fontSize(6.5).text(`Pickup: ${safe(l.location.name)}${l.location.address?' · '+safe(l.location.address):''}`);doc.font('Helvetica').fontSize(6.5).text(`${n(l.quantity)} ${l.saleUnit} × ${money(l.unitPrice)} = ${money(l.grossAmount)}`);if(n(l.vatAmount))doc.text(`VAT: ${money(l.vatAmount)}`);doc.moveDown(.25)}
  }else{
    const left=doc.page.margins.left,width=doc.page.width-left-doc.page.margins.right;
    const cols=[.05,.30,.10,.10,.15,.10,.20].map(v=>v*width),heads=['#','Item','Unit','Qty','Unit Price','VAT','Total'];
    let y=doc.y;doc.font('Helvetica-Bold').fontSize(8);let x0=left;heads.forEach((h,i)=>{doc.text(h,x0,y,{width:cols[i]});x0+=cols[i]});doc.y=y+18;line(doc,doc.y);doc.moveDown(.25);
    for(const l of x.lines){y=doc.y;x0=left;const vals=[l.lineNo,l.item.name+(l.location?` · Pickup: ${l.location.name}`:''),l.saleUnit,n(l.quantity),money(l.unitPrice),money(l.vatAmount),money(l.grossAmount)];doc.font('Helvetica').fontSize(8);vals.forEach((v,i)=>{doc.text(safe(v),x0,y,{width:cols[i],height:28,ellipsis:true});x0+=cols[i]});doc.y=y+30;line(doc,doc.y);doc.moveDown(.2)}
  }
  doc.moveDown(.4);
  const pending=x.cheques.filter(c=>['HELD','PRESENTED'].includes(c.status)).reduce((a,c)=>a+n(c.amount),0);
  kv(doc,'Subtotal',money(x.subtotal),spec);if(n(x.discountAmount))kv(doc,'Discount',money(x.discountAmount),spec);if(n(x.vatAmount))kv(doc,'VAT',money(x.vatAmount),spec);kv(doc,'INVOICE TOTAL',money(x.totalAmount),spec);kv(doc,'Amount Paid',money(x.amountPaid),spec);kv(doc,'Outstanding',money(x.outstanding),spec);if(pending)kv(doc,'Pending PDC Cover',money(pending),spec);
  if(x.notes){doc.moveDown(.4);doc.font('Helvetica-Bold').fontSize(spec.pos?7:9).text('Notes');doc.font('Helvetica').text(safe(x.notes));}
  if(x.payments.length||x.cheques.length){doc.moveDown(.55);line(doc,doc.y);doc.moveDown(.45);doc.font('Helvetica-Bold').fontSize(spec.pos?8:11).text('SETTLEMENT / PDC HISTORY');doc.moveDown(.25);for(const p of x.payments)doc.font('Helvetica').fontSize(spec.pos?6.5:8).text(`${d(p.paymentDate)} · ${p.method} · ${p.reference||p.paymentNo} · ${money(p.amount)}`);for(const c of x.cheques)doc.font('Helvetica').fontSize(spec.pos?6.5:8).text(`${d(c.dateReceived)} · PDC ${c.chequeNo} · ${c.status} · ${money(c.amount)}`)}
  if(x.returns?.length){doc.moveDown(.45);line(doc,doc.y);doc.moveDown(.35);doc.font('Helvetica-Bold').fontSize(spec.pos?8:10).text('CREDIT NOTES / RETURNS');for(const z of x.returns)doc.font('Helvetica').fontSize(spec.pos?6.5:8).text(`${d(z.returnDate)} · ${z.returnNo} · Credit ${money(z.creditAmount)} · Refund due ${money(Math.max(0,n(z.refundDue)-n(z.refundedAmount)))}`)}
  footer(doc,spec);doc.end();
});

r.get('/customers/:id/statement.pdf',permit('RECEIVABLE_VIEW'),async(req,res)=>{
  const customer=await prisma.customer.findUnique({where:{id:req.params.id}});if(!customer)return res.status(404).json({message:'Customer not found.'});
  const [invoices,payments,cheques,returns,refunds]=await Promise.all([
    prisma.salesInvoice.findMany({where:{customerId:customer.id},orderBy:{invoiceDate:'asc'}}),
    prisma.salesPayment.findMany({where:{customerId:customer.id},orderBy:{paymentDate:'asc'}}),
    prisma.customerCheque.findMany({where:{customerId:customer.id},orderBy:{dateReceived:'asc'}}),
    prisma.salesReturn.findMany({where:{customerId:customer.id},orderBy:{returnDate:'asc'}}),
    prisma.customerRefund.findMany({where:{customerId:customer.id},orderBy:{refundDate:'asc'}})
  ]);
  const entries=[];if(n(customer.openingBalance)!==0)entries.push({date:customer.openingBalanceDate||customer.createdAt,type:'OPENING',reference:'OPENING',debit:n(customer.openingBalance),credit:0});
  for(const x of invoices.filter(x=>x.status!=='CANCELLED'))entries.push({date:x.invoiceDate,type:'INVOICE',reference:x.invoiceNo,debit:n(x.totalAmount),credit:0});
  for(const x of payments)entries.push({date:x.paymentDate,type:`PAYMENT ${x.method}`,reference:x.reference||x.paymentNo,debit:0,credit:n(x.amount)});
  for(const x of returns)entries.push({date:x.returnDate,type:'CREDIT NOTE',reference:x.returnNo,debit:0,credit:n(x.creditAmount)});
  for(const x of refunds)entries.push({date:x.refundDate,type:'CUSTOMER REFUND',reference:x.refundNo,debit:n(x.amount),credit:0});
  entries.sort((a,b)=>new Date(a.date)-new Date(b.date));let bal=0;for(const e of entries){bal+=e.debit-e.credit;e.balance=bal;}
  const spec=pageSpec(req.query.size,entries.length+cheques.length),doc=makeDoc(res,`${customer.customerCode}_statement_${spec.label.replaceAll(' ','_')}.pdf`,spec);
  heading(doc,'CUSTOMER STATEMENT',`${customer.customerCode} · ${customer.name}`,spec);kv(doc,'Customer',customer.name,spec);kv(doc,'Phone',customer.phone||'—',spec);kv(doc,'Address',customer.address||'—',spec);kv(doc,'Statement Date',d(new Date()),spec);doc.moveDown(.5);line(doc,doc.y);doc.moveDown(.4);
  if(spec.pos){for(const e of entries){doc.font('Helvetica-Bold').fontSize(7).text(`${d(e.date)} · ${e.type}`);doc.font('Helvetica').fontSize(6.5).text(`${e.reference} | Dr ${money(e.debit)} | Cr ${money(e.credit)} | Bal ${money(e.balance)}`);doc.moveDown(.2)}}
  else{const left=doc.page.margins.left,width=doc.page.width-left-doc.page.margins.right,cols=[.12,.16,.20,.16,.16,.20].map(v=>v*width),heads=['Date','Type','Reference','Debit','Credit','Balance'];let y=doc.y,x0=left;doc.font('Helvetica-Bold').fontSize(8);heads.forEach((h,i)=>{doc.text(h,x0,y,{width:cols[i]});x0+=cols[i]});doc.y=y+18;line(doc,doc.y);doc.moveDown(.2);for(const e of entries){y=doc.y;x0=left;const vals=[d(e.date),e.type,e.reference,money(e.debit),money(e.credit),money(e.balance)];doc.font('Helvetica').fontSize(7.5);vals.forEach((v,i)=>{doc.text(safe(v),x0,y,{width:cols[i],height:24,ellipsis:true});x0+=cols[i]});doc.y=y+26;line(doc,doc.y);doc.moveDown(.15)}}
  doc.moveDown(.35);doc.font('Helvetica-Bold').fontSize(spec.pos?8:11).text(`CLOSING BALANCE: ${money(bal)}`);
  if(cheques.length){doc.moveDown(.5);line(doc,doc.y);doc.moveDown(.4);doc.font('Helvetica-Bold').fontSize(spec.pos?8:10).text('CHEQUE HISTORY');for(const c of cheques)doc.font('Helvetica').fontSize(spec.pos?6.5:8).text(`${d(c.dateReceived)} · ${c.chequeNo} · ${c.drawerBank} · ${c.status} · ${money(c.amount)}`)}
  footer(doc,spec);doc.end();
});

export default r;
